/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedAssistantLoadingRouteImport } from './routes/_authenticated/assistant-loading'
import { Route as AuthenticatedAssistantErrorRouteImport } from './routes/_authenticated/assistant-error'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantLoadingRoute =
  AuthenticatedAssistantLoadingRouteImport.update({
    id: '/assistant-loading',
    path: '/assistant-loading',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantErrorRoute =
  AuthenticatedAssistantErrorRouteImport.update({
    id: '/assistant-error',
    path: '/assistant-error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/assistant-error': typeof AuthenticatedAssistantErrorRoute
  '/assistant-loading': typeof AuthenticatedAssistantLoadingRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/assistant-error': typeof AuthenticatedAssistantErrorRoute
  '/assistant-loading': typeof AuthenticatedAssistantLoadingRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/assistant-error': typeof AuthenticatedAssistantErrorRoute
  '/_authenticated/assistant-loading': typeof AuthenticatedAssistantLoadingRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/assistant-error'
    | '/assistant-loading'
    | '/team'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistant'
    | '/assistant-error'
    | '/assistant-loading'
    | '/team'
    | '/workspace'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/assistant-error'
    | '/_authenticated/assistant-loading'
    | '/_authenticated/team'
    | '/_authenticated/workspace'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant-loading': {
      id: '/_authenticated/assistant-loading'
      path: '/assistant-loading'
      fullPath: '/assistant-loading'
      preLoaderRoute: typeof AuthenticatedAssistantLoadingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant-error': {
      id: '/_authenticated/assistant-error'
      path: '/assistant-error'
      fullPath: '/assistant-error'
      preLoaderRoute: typeof AuthenticatedAssistantErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAssistantErrorRoute: typeof AuthenticatedAssistantErrorRoute
  AuthenticatedAssistantLoadingRoute: typeof AuthenticatedAssistantLoadingRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAssistantErrorRoute: AuthenticatedAssistantErrorRoute,
  AuthenticatedAssistantLoadingRoute: AuthenticatedAssistantLoadingRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
